version: '3.7'

services:
  clrkio:
    image: docker.pkg.github.com/williamjacksn/clrkio/clrkio
    build: .
    environment:
      DB: postgres://postgres:postgres@postgres/postgres
    ports:
      - 5000:5000

  postgres:
    image: postgres:11.5-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/11
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
