version: '3.8'

services:
  clrkio:
    image: ghcr.io/williamjacksn/clrkio
    build: .
    environment:
      DB: postgres://postgres:postgres@postgres/postgres
    ports:
      - 8080:8080

  postgres:
    image: postgres:11.10-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/11
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
